### ISSUE TITLE
Avoid parameter method names that provoke conflicts with class members names.

### ISSUE THREAD

**Issue by sarychuk** [cmput402w2016/Team-3--Kaleidoscope#7]
155 defects in 30 files. Fixing Maintainability.

**Comment by sarychuk** [comment]
A lot of the parameter method names are @Override of method names that exist already and Hu has just changed what they do, so we cannot change their names.

**Comment by timoteialbu** [comment]
Yeah so if you managed to fix the ones you could, then close this issue
